spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 950223
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
  jpa:
    hibernate:
      ddl-auto: update