spring:
  security:
    success-forward-url: '${controller.auth.login.loginSuccess}'
    failure-forward-url: '${controller.auth.login.loginFailure}'
    logout-success-url: '${controller.auth.login.logout}'
    authentication-entry-point-url: '${controller.auth.login.unauthorized}'
    access-denied-url: '${controller.auth.login.accessDenied}'
    maximum-sessions: 1
    max-sessions-prevents-login: false
    anonymous-username: 'anonymous'
    cors:
      allowed-origins:
        - '*'
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
      allow-credentials: true
      max-age: 1800
      path: '/**'
    token:
      ignore-authentication-request-urls:
        - '${controller.fileUpload.root}${controller.fileUpload.getFile}'
        - '${controller.auth.login.accessDenied}'
      requires-authentication-request-url: '/**'
      writer-request-url: '${controller.auth.login.loginSuccess}'