spring:
  security:
    cors:
      allowed-origins:
        - '*'
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
      allow-credentials: true
      max-age: 1800
    token:
      ignore-authentication-request-urls:
        - '/file/**'
        - '/accessDenied'
      requires-authentication-request-url: '/**'