spring:
  security:
    success-forward-url: '/loginSuccess'
    failure-forward-url: '/loginFailure'
    logout-success-url: '/logoutSuccess'
    authentication-entry-point-url: '/unauthorized'
    access-denied-url: '/accessDenied'
    maximum-sessions: 1
    max-sessions-prevents-login: false
    cors:
      allowed-origins:
        - '*'
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
      allow-credentials: true
      max-age: 1800
      path: '/**'
    token:
      ignore-authentication-request-urls:
        - '/file/**'
        - '/accessDenied'
      requires-authentication-request-url: '/**'
      writer-request-url: '/loginSuccess'