spring:
  security:
    cors:
      allowed-origins:
        - '*'
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
      allow-credentials: true
      max-age: 1800
    token:
      ignore-request-url: '/file/**'
      requires-authentication-request-url: '/**'